### ISSUE TITLE
Great job. 1 suggestion

### ISSUE THREAD

**Issue by xberg** [skfaisal93/AnyWhereInFiles#1]
Hi,
I like this! 
Do you think it would make sense to also add a filter on file type? For instance that the user can only search for .PHP or .TXT or .CSS?
I have a million images that I really do not need to search :)

**Comment by skfaisal93** [comment]
Thank you or your suggestion. I will definitely add this feature.

**Comment by skfaisal93** [comment]
Added this option. check anywhereinfiles-1.4.php
